package api

import (
	"encoding/json"
	"io"
	"net/http"
	"sync"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/Yata-Dash/Yata-Dash/internal/version"
)

// Update check: compares this instance's app / definitions / pathways versions
// against versions.json on the repo's main branch (regenerated by
// tools/genversions whenever defs change). PRIVACY: the remote fetch contacts
// raw.githubusercontent.com and runs ONLY when the user clicks "Check for
// updates" or has explicitly enabled the daily auto-check — never silently.
//
// Version semantics (all lexicographically comparable):
//   app      — "Beta-YYYYMMDD[letter]" from internal/version
//   defs     — max last_updated (YYYY-MM-DD) across bundled tracker defs
//   pathways — routes.json source.updated (YYYY-MM): the upstream DATA date,
//              not when we fetched it (falls back to source.fetched if absent)

const remoteManifestURL = "https://raw.githubusercontent.com/Yata-Dash/Yata-Dash/main/versions.json"

// VersionsManifest is versions.json — the repo-side source of truth.
type VersionsManifest struct {
	App      string `json:"app"`
	Defs     string `json:"defs"`
	Pathways string `json:"pathways"`
}

type updateComponent struct {
	Current   string `json:"current"`
	Latest    string `json:"latest,omitempty"` // "" until a check has run
	Available bool   `json:"update_available"`
}

type updateStatus struct {
	App       updateComponent `json:"app"`
	Defs      updateComponent `json:"defs"`
	Pathways  updateComponent `json:"pathways"`
	CheckedAt int64           `json:"checked_at,omitempty"` // unix seconds; 0 = never
	Error     string          `json:"error,omitempty"`      // last check's failure, if any
}

var (
	updMu        sync.Mutex
	updRemote    *VersionsManifest
	updCheckedAt time.Time
	updErr       string
)

var updateClient = &http.Client{Timeout: 15 * time.Second}

func registerUpdates(r chi.Router, d *Deps) {
	r.Get("/updates", getUpdates(d))
	r.Post("/updates/check", checkUpdates(d))
}

// localVersions computes this instance's versions from its own data.
func localVersions(d *Deps) VersionsManifest {
	m := VersionsManifest{App: version.Version}
	for _, td := range d.Reg.Trackers() {
		if td.LastUpdated > m.Defs {
			m.Defs = td.LastUpdated
		}
	}
	for _, tt := range d.Reg.Types() {
		if tt.LastUpdated > m.Defs {
			m.Defs = tt.LastUpdated
		}
	}
	if d.Paths != nil {
		// The pathways "version" is the upstream DATA date, not when we fetched
		// it. Fall back to fetched for pre-`updated` snapshots.
		m.Pathways = d.Paths.Source.Updated
		if m.Pathways == "" {
			m.Pathways = d.Paths.Source.Fetched
		}
	}
	return m
}

// buildStatus merges local versions with the cached remote manifest.
func buildStatus(d *Deps) updateStatus {
	local := localVersions(d)
	updMu.Lock()
	remote, at, errMsg := updRemote, updCheckedAt, updErr
	updMu.Unlock()

	newer := func(cur, latest string) bool { return latest != "" && cur != "" && latest > cur }
	s := updateStatus{
		App:      updateComponent{Current: local.App},
		Defs:     updateComponent{Current: local.Defs},
		Pathways: updateComponent{Current: local.Pathways},
		Error:    errMsg,
	}
	if !at.IsZero() {
		s.CheckedAt = at.Unix()
	}
	if remote != nil {
		s.App.Latest, s.App.Available = remote.App, newer(local.App, remote.App)
		s.Defs.Latest, s.Defs.Available = remote.Defs, newer(local.Defs, remote.Defs)
		s.Pathways.Latest, s.Pathways.Available = remote.Pathways, newer(local.Pathways, remote.Pathways)
	}
	return s
}

// fetchRemoteManifest pulls versions.json from the repo and caches the result
// (also caching failures so the UI can show what went wrong).
func fetchRemoteManifest(d *Deps, url string) error {
	resp, err := updateClient.Get(url)
	var m VersionsManifest
	if err == nil {
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			err = &httpErr{resp.StatusCode}
		} else {
			var body []byte
			if body, err = io.ReadAll(io.LimitReader(resp.Body, 64<<10)); err == nil {
				err = json.Unmarshal(body, &m)
			}
		}
	}
	updMu.Lock()
	defer updMu.Unlock()
	updCheckedAt = time.Now()
	if err != nil {
		updErr = err.Error()
		d.logWarnf("updates: check failed — %v", err)
		return err
	}
	updErr = ""
	updRemote = &m
	return nil
}

type httpErr struct{ code int }

func (e *httpErr) Error() string { return "http " + http.StatusText(e.code) }

// GET /api/updates — local versions + the last check's result (never fetches).
func getUpdates(d *Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, _ *http.Request) {
		jsonOK(w, buildStatus(d))
	}
}

// POST /api/updates/check — contact the repo now, then return fresh status.
func checkUpdates(d *Deps) http.HandlerFunc {
	return func(w http.ResponseWriter, _ *http.Request) {
		_ = fetchRemoteManifest(d, remoteManifestURL)
		s := buildStatus(d)
		if s.Error == "" {
			d.logInfof("updates: checked — app %s/%s defs %s/%s pathways %s/%s",
				s.App.Current, s.App.Latest, s.Defs.Current, s.Defs.Latest,
				s.Pathways.Current, s.Pathways.Latest)
		}
		jsonOK(w, s)
	}
}

// StartUpdateChecker runs the OPT-IN daily background check. The setting is
// re-read every tick so enabling/disabling needs no restart; nothing is
// fetched while the toggle is off.
func StartUpdateChecker(d *Deps) {
	go func() {
		time.Sleep(1 * time.Minute) // let startup settle
		for {
			if d.Cfg.Settings().UpdateCheckAuto {
				if err := fetchRemoteManifest(d, remoteManifestURL); err == nil {
					s := buildStatus(d)
					if s.App.Available || s.Defs.Available || s.Pathways.Available {
						d.logInfof("updates: available — app %s→%s, defs %s→%s, pathways %s→%s",
							s.App.Current, s.App.Latest, s.Defs.Current, s.Defs.Latest,
							s.Pathways.Current, s.Pathways.Latest)
					}
				}
			}
			time.Sleep(24 * time.Hour)
		}
	}()
}
